### ISSUE TITLE
Your Memberships page add context

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#225]
- Unclear whether a membership is standard or premium, suggested to add a column for "Membership Type" 

- Unlock date for standard membership should be changed to "Anytime" or "Unlocked" 

- Unlock time is at an exact time, not just date, so this context should be shown in some way. Either include date & time or add mouseover text with the full date & time

**Comment by rojogorilla** [comment]
https://github.com/Theopetra/theo-finance-app/commit/84b235b5157626429e832d7985a60be0b9b6c20f
