### ISSUE TITLE
Add confirmation dialogue for slashing penalty 

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#226]
From Jab: 
When clicking on "Unstake Early", there should DEFINITELY be a confirmation dialog before Metamask pops up. That dialog is actually a good place to put a link to a deeper explanation about how and why slashing works.  

Love that little (i) for slashing penalty. We should probably have a link to a deeper explanation there too?  

BUT 

People will have tons of questions on "How much?" "Why?" and will be angry and disappointed if slashed "without warning". Remember, users don't read... Especially not the fine print. Have to put it in their face. Repeat the same info in a confirm dialog.

**Comment by rojogorilla** [comment]
completed and merged to develop
