### ISSUE TITLE
Metamask approval failure when setting custom spending cap

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#227]
When the user sets a custom spending cap that is not the default value, the transaction fails. Appears to be an issue between wagmi and metamask.

**Comment by rojogorilla** [comment]
Missed this comment but yes that's my observation as well. Really seems to be a safety mechanism with the latest MM update. Apps cannot dictate what amount is approved and requires deliberate action on the part of the user. To help with this I've implemented some UI changes to handle the failed transaction and inform the user what went wrong.





<img width="562" alt="Screen Shot 2023-04-22 at 9 30 08 AM" src="https://user-images.githubusercontent.com/100251516/233791032-74c8afb8-c0c8-4dec-8b21-8808a6c112f9.png">
<img width="737" alt="Screen Shot 2023-04-22 at 9 30 51 AM" src="https://user-images.githubusercontent.com/100251516/233791033-2a8b68dd-e626-4d4e-ad64-b24866844f2e.png">
