### ISSUE TITLE
Make slashing penalty clearer when confirming premium membership

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#228]
Confirmation card for premium membership states that "You can unstake at any time" but without a clear explanation that this will incur a slashing penalty. 

Suggested change: 
Change dialogue to
"You can unstake at any time, but won't be eligible for ETH rebates. Slashing penalties apply if unstaked early." 

Include additional confirmation/disclaimer card that explains slashing penalties in detail, as in issue #226

**Comment by rojogorilla** [comment]
https://github.com/Theopetra/theo-finance-app/commit/84b235b5157626429e832d7985a60be0b9b6c20f
