### ISSUE TITLE
Add additional premium membership rewards column for slashing pool bonus

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#229]
Seeing rewards inconsistent with the expected APY due to the slashing pool may cause confusion. Suggested to add a second column which shows only the slashing rewards

**Comment by rojogorilla** [comment]
@Cryptofowl and I settled on reusing the penalty UI for immature stakes for the reward bonus for mature stakes.

**Comment by rojogorilla** [comment]
In addition to the above we should show the acumulating rewards in table. The data comes from here
>It gets returned from the user purchases provider as slashingPoolRewards

**Comment by rojogorilla** [comment]
![Screen Shot 2023-04-22 at 10 37 00 AM](https://user-images.githubusercontent.com/100251516/233793580-9b6e3c96-723a-45a7-a080-8e88ec83700d.png)

**Comment by rojogorilla** [comment]
pushed this change to dev
![Screen Shot 2023-04-22 at 10 42 23 AM](https://user-images.githubusercontent.com/100251516/233793824-f29f6b38-ae41-454e-a385-77fcc069f922.png)
