### ISSUE TITLE
Max payout defaults to 0 before a market is selected

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#242]
The max payout error will show up for any amount when the page first loads and when markets are selected from the dropdown menu. The issue only resolves once the market is set using the buttons from the table. Recommended to set a default market and update the max payout value when it is loaded.

**Comment by rojogorilla** [comment]
Should be resolved with this commit but want to leave this open for a bit.
https://github.com/Theopetra/theo-finance-app/commit/fb960466d11119436b985ba39306b1a3aabc62e2
