### ISSUE TITLE
Change ambiguous terms

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#251]
The connection between "Term" and "Market" is ambiguous and should be consistent.

Change "Terms" to "Choose lockup time" 

Change "Set Market" to "Select" 

Change "All markets" to "Discount Buy Options" 

Change "Duration" to "Lock time" 

add 2 decimals to the discount rate

Add an info box somewhere on the page – maybe use that empty space on the right? - that explains that “When you discount buy, your $THEO is locked for a period of time before you can claim them. The longer the lock time, the larger the discount.” This is obvious to us but may not at all be clear to a first-time visitor.

**Comment by Cryptofowl** [comment]
Rename "Discount Price" to "$THEO Discount Price" 

Adjust decimals on discount price in all markets table. Appears to be correct in the discount buy form, but not there

**Comment by rojogorilla** [comment]
These are addressed here 
https://github.com/Theopetra/theo-finance-app/commit/9d18a9b7781e00343d705e5e9b7c7f60ac630214

<img width="1061" alt="Screen Shot 2023-06-28 at 6 13 38 AM" src="https://github.com/Theopetra/theo-finance-app/assets/100251516/45537953-3dbe-4530-b316-98a48f801534">
