### ISSUE TITLE
UI Cleanup

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#252]
Some values seem to be showing up where they're not supposed to, either due to typos or overflow elsewhere.  See doc for reference screenshots for JW7, JW11

Remove confirm buy page "109" 

Date formatting breaks occasionally,

**Comment by Cryptofowl** [comment]
Should be reviewed for typos as well

**Comment by rojogorilla** [comment]
@Cryptofowl can you upload screenshots here? Doc i have is outdated

**Comment by Cryptofowl** [comment]
![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/5b25a5ee-cc8a-4d7b-a8d5-a5ccf995c235)
![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/2717b5dd-d10e-4526-9ee8-e56023eb54f3)

**Comment by Cryptofowl** [comment]
![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/10e3aea8-2674-4184-a28d-c2a046eb81e7)
![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/3987b316-b11a-4fd3-aa07-11ec0b2ec350)

**Comment by Cryptofowl** [comment]
On successful claim page, date formatting error and wrong token amount displayed (also a date format) 

![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/6e4b0b7d-30cf-45a8-ae03-4ff40f0964e1)

**Comment by rojogorilla** [comment]
time format and random number fixed here
https://github.com/Theopetra/theo-finance-app/commit/b9712c86ba98361bc5d9d477a502c06d9a06ab86
