### ISSUE TITLE
Market data not loading on first visit in staging environment

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#255]
Haven't been able to recreate this locally, but in the staging environment the market data doesn't seem to load properly. $THEO price is set to 0, and the correct markets appear but can't be selected in the lockup time dropdown menu. Error resolves after refreshing the page, and selecting a market in the discount buy options table. 

![image](https://github.com/Theopetra/theo-finance-app/assets/86430321/54cb191a-427f-4a97-a251-2adfeaf696dc)

**Comment by Cryptofowl** [comment]
"Purchase NaN THEO" appears when using the max button before selecting a market

**Comment by rojogorilla** [comment]
There was a state/useEffect issue on load. 
https://github.com/Theopetra/theo-finance-app/commit/b5cafe718bf952051d281c59c3b795be7756b6d2
