### ISSUE TITLE
Max payout doesn't update with the "Choose lockup time" options

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#258]
Leads to "Exceeds max payout" error at any quantity. Resolves after selecting market in discount buy options table

**Comment by rojogorilla** [comment]
I think the other issue and this were related. 
https://github.com/Theopetra/theo-finance-app/commit/b5cafe718bf952051d281c59c3b795be7756b6d2

https://github.com/Theopetra/theo-finance-app/issues/262
