### ISSUE TITLE
Switch out media on dashboard page

### ISSUE THREAD

**Issue by Cryptofowl** [Theopetra/theo-finance-app#267]
Youtube video should be switched over to the new protocol explainer gif 

https://github.com/Theopetra/theo-finance-app/assets/86430321/e450f6ac-a98d-45af-b8e1-6834c32b3c76

**Comment by rojogorilla** [comment]
done via https://github.com/Theopetra/theo-finance-app/commit/ae469caa970a773c2a3551c03063527ed817e47a
